import type { NextPage } from 'next';
import Head from 'next/head';
import HomePage from './HomePage/HomePage';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Masteri-site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </>
  );
};

export default Home;
